# Generated by Django 6.0.2 on 2026-02-05 10:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CharacteristicGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField()),
            ],
            options={
                'db_table': 'characteristic_groups',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField()),
                ('color', models.CharField()),
                ('ssd', models.CharField()),
                ('manufacturer', models.CharField()),
                ('price', models.IntegerField()),
                ('promo_price', models.IntegerField(null=True)),
                ('code', models.CharField()),
                ('num_reviews', models.IntegerField()),
                ('screen_diagonal', models.FloatField()),
                ('resolution', models.CharField()),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('value', models.CharField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='products.characteristicgroup')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='products.product')),
            ],
            options={
                'db_table': 'characteristics',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.CharField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
            options={
                'db_table': 'product_images',
            },
        ),
    ]
